import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const chicagoFont = localFont({ src: './ChicagoFLF.woff2', variable: '--chicago' })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={chicagoFont.variable}>{children}</body>
    </html>
  );
}
